ALTER TABLE [Object] NOCHECK CONSTRAINT ALL

INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('TYPE','MAIN','TYPE','MAIN','Type','TYPE','fullName:Tesseract.Object',NULL,NULL,NULL,'SYS')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('SESS','MAIN','TYPE','MAIN','Tesseract.Session','TYPE','fullName:Tesseract.Session, ..',NULL,NULL,NULL,'SYS')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('MAIN','MAIN','SESS','MAIN','Main Session','SESS','sessionOwner=SYSTEM00000,shared=true',NULL,NULL,NULL,'SYS')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('USER','MAIN','TYPE','MAIN','Tesseract.User','TYPE','fullName:Tesseract.User,…',NULL,NULL,NULL,'SYS')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('SYS','MAIN','USER','MAIN','system','USER','login=system,firstName=SYSTEM,memberOf=…',NULL,NULL,NULL,'SYS')

ALTER TABLE [Object] WITH CHECK CHECK CONSTRAINT ALL

INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('BA0ADggMBg4','MAIN','USER','MAIN','bob','USER','login=bob,firstName=Bob,memberOf=Developers',NULL,NULL,NULL,'SYS')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('CAABCwUNBgA','MAIN','TYPE','MAIN','Tessesract.Trading.Deal','TYPE','fullName:Tesseract.Trading.Deal, ..',NULL,NULL,NULL,'BA0ADggMBg4')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('CgMJAAoHCwc','MAIN','USER','MAIN','alice','USER','login=alice,firstName=Alice,memberOf=…',NULL,NULL,NULL,'BA0ADggMBg4')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('Cw4LAQ8KCwk','MAIN','CAABCwUNBgA','MAIN','deal_1','CAABCwUNBgA','name:deal_1, tradeDate: 01/10/2018,price=110,…',NULL,NULL,NULL,'CgMJAAoHCwc')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('DAoHCg0DCgI','MAIN','SESS','MAIN','2018-05-10:Alice:What-if','SESS','sessionOwner=CgMJAAoHCwc,shared=true',NULL,NULL,NULL,'CgMJAAoHCwc')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('Cw4LAQ8KCwk','DAoHCg0DCgI','CAABCwUNBgA','MAIN','deal_1','CAABCwUNBgA','name:deal_1, tradeDate: 01/10/2018,price=100,…',NULL,NULL,NULL,'CgMJAAoHCwc')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('AAEBDAINCgE','MAIN','SESS','MAIN','2018-10-10:Bob:Work item 1234','SESS','sessionOwner=BA0ADggMBg4,shared=false',NULL,NULL,NULL,'BA0ADggMBg4')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('CAABCwUNBgA','AAEBDAINCgE','TYPE','MAIN','Tessesract.Trading.Deal','TYPE','fullName:Tesseract.Trading.Deal, newProperty=…',NULL,NULL,NULL,'BA0ADggMBg4')
INSERT INTO [dbo].[Object] ([ID],[SessionID],[TypeID],[TypeSessionID],[Name],[NameTypeID],[Data],[PartitionDate],[PartitionFlag1],[PartitionFlag2],[ModifiedByID]) VALUES ('Cw4LAQ8KCwk','AAEBDAINCgE','CAABCwUNBgA','AAEBDAINCgE','deal_1','CAABCwUNBgA','name:deal_1, tradeDate: 01/10/2018,newPropety=A,…',NULL,NULL,NULL,'BA0ADggMBg4')
